// <auto-generated />
namespace Argos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ServiceLocatableField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ServiceLocatableField));
        
        string IMigrationMetadata.Id
        {
            get { return "201802140432546_ServiceLocatableField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
